// Code generated by go-swagger; DO NOT EDIT.

package resource_plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewApplyResourcePluginParams creates a new ApplyResourcePluginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplyResourcePluginParams() *ApplyResourcePluginParams {
	return &ApplyResourcePluginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplyResourcePluginParamsWithTimeout creates a new ApplyResourcePluginParams object
// with the ability to set a timeout on a request.
func NewApplyResourcePluginParamsWithTimeout(timeout time.Duration) *ApplyResourcePluginParams {
	return &ApplyResourcePluginParams{
		timeout: timeout,
	}
}

// NewApplyResourcePluginParamsWithContext creates a new ApplyResourcePluginParams object
// with the ability to set a context for a request.
func NewApplyResourcePluginParamsWithContext(ctx context.Context) *ApplyResourcePluginParams {
	return &ApplyResourcePluginParams{
		Context: ctx,
	}
}

// NewApplyResourcePluginParamsWithHTTPClient creates a new ApplyResourcePluginParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplyResourcePluginParamsWithHTTPClient(client *http.Client) *ApplyResourcePluginParams {
	return &ApplyResourcePluginParams{
		HTTPClient: client,
	}
}

/*
ApplyResourcePluginParams contains all the parameters to send to the API endpoint

	for the apply resource plugin operation.

	Typically these are written to a http.Request.
*/
type ApplyResourcePluginParams struct {

	/* Data.

	   Request to create or update a resource plugin
	*/
	Data *models.ResourcePlugin

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* PluginName.

	   Resource plugin name
	*/
	PluginName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apply resource plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyResourcePluginParams) WithDefaults() *ApplyResourcePluginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apply resource plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyResourcePluginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithTimeout(timeout time.Duration) *ApplyResourcePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithContext(ctx context.Context) *ApplyResourcePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithHTTPClient(client *http.Client) *ApplyResourcePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithData(data *models.ResourcePlugin) *ApplyResourcePluginParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetData(data *models.ResourcePlugin) {
	o.Data = data
}

// WithOrgName adds the orgName to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithOrgName(orgName string) *ApplyResourcePluginParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithPluginName adds the pluginName to the apply resource plugin params
func (o *ApplyResourcePluginParams) WithPluginName(pluginName string) *ApplyResourcePluginParams {
	o.SetPluginName(pluginName)
	return o
}

// SetPluginName adds the pluginName to the apply resource plugin params
func (o *ApplyResourcePluginParams) SetPluginName(pluginName string) {
	o.PluginName = pluginName
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyResourcePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param pluginName
	if err := r.SetPathParam("pluginName", o.PluginName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
