// Code generated by go-swagger; DO NOT EDIT.

package plan_execution_logs

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new plan execution logs API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new plan execution logs API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new plan execution logs API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for plan execution logs API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption {
	return func(r *runtime.ClientOperation) {
		r.ProducesMediaTypes = []string{mime}
	}
}

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"application/json"}
}

// WithAcceptTextEventStream sets the Accept header to "text/event-stream".
func WithAcceptTextEventStream(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/event-stream"}
}

// WithAcceptTextPlain sets the Accept header to "text/plain".
func WithAcceptTextPlain(r *runtime.ClientOperation) {
	r.ProducesMediaTypes = []string{"text/plain"}
}

// ClientService is the interface for Client methods
type ClientService interface {
	DownloadStepLog(params *DownloadStepLogParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*DownloadStepLogOK, *DownloadStepLogPartialContent, error)

	StreamPlanExecutionLogs(params *StreamPlanExecutionLogsParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*StreamPlanExecutionLogsOK, error)

	StreamPlanExecutionStepLogs(params *StreamPlanExecutionStepLogsParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*StreamPlanExecutionStepLogsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DownloadStepLog downloads a step log

Returns the captured stdout or stderr for a specific step. Inlined values are served directly; large logs are proxied from S3.
*/
func (a *Client) DownloadStepLog(params *DownloadStepLogParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*DownloadStepLogOK, *DownloadStepLogPartialContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDownloadStepLogParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "download-step-log",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/plans/executions/{executionID}/steps/{stepID}/logs/download",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DownloadStepLogReader{formats: a.formats, writer: writer},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}

	// several success responses have to be checked
	switch value := result.(type) {
	case *DownloadStepLogOK:
		return value, nil, nil
	case *DownloadStepLogPartialContent:
		return nil, value, nil
	}

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for plan_execution_logs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
StreamPlanExecutionLogs streams aggregated plan logs

Stream live logs for all steps of a plan execution, multiplexed into a single stream.
*/
func (a *Client) StreamPlanExecutionLogs(params *StreamPlanExecutionLogsParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*StreamPlanExecutionLogsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewStreamPlanExecutionLogsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "stream-plan-execution-logs",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/plans/executions/{executionID}/logs/live",
		ProducesMediaTypes: []string{"text/event-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StreamPlanExecutionLogsReader{formats: a.formats, writer: writer},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*StreamPlanExecutionLogsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for stream-plan-execution-logs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
StreamPlanExecutionStepLogs streams step logs

Stream live stdout or stderr logs for a specific step of a plan execution.
*/
func (a *Client) StreamPlanExecutionStepLogs(params *StreamPlanExecutionStepLogsParams, authInfo runtime.ClientAuthInfoWriter, writer io.Writer, opts ...ClientOption) (*StreamPlanExecutionStepLogsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewStreamPlanExecutionStepLogsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "stream-plan-execution-step-logs",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/plans/executions/{executionID}/steps/{stepID}/logs/live",
		ProducesMediaTypes: []string{"text/event-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StreamPlanExecutionStepLogsReader{formats: a.formats, writer: writer},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*StreamPlanExecutionStepLogsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for stream-plan-execution-step-logs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
