// Code generated by go-swagger; DO NOT EDIT.

package plan_tags

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// GetPlanTagReader is a Reader for the GetPlanTag structure.
type GetPlanTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlanTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPlanTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPlanTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPlanTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewGetPlanTagBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{orgName}/plan-tags/{planTagName}] get-plan-tag", response, response.Code())
	}
}

// NewGetPlanTagOK creates a GetPlanTagOK with default headers values
func NewGetPlanTagOK() *GetPlanTagOK {
	return &GetPlanTagOK{}
}

/*
GetPlanTagOK describes a response with status code 200, with default header values.

OK
*/
type GetPlanTagOK struct {
	Payload *models.PlanTag
}

// IsSuccess returns true when this get plan tag o k response has a 2xx status code
func (o *GetPlanTagOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get plan tag o k response has a 3xx status code
func (o *GetPlanTagOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan tag o k response has a 4xx status code
func (o *GetPlanTagOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plan tag o k response has a 5xx status code
func (o *GetPlanTagOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan tag o k response a status code equal to that given
func (o *GetPlanTagOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get plan tag o k response
func (o *GetPlanTagOK) Code() int {
	return 200
}

func (o *GetPlanTagOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagOK %s", 200, payload)
}

func (o *GetPlanTagOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagOK %s", 200, payload)
}

func (o *GetPlanTagOK) GetPayload() *models.PlanTag {
	return o.Payload
}

func (o *GetPlanTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlanTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPlanTagBadRequest creates a GetPlanTagBadRequest with default headers values
func NewGetPlanTagBadRequest() *GetPlanTagBadRequest {
	return &GetPlanTagBadRequest{}
}

/*
GetPlanTagBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetPlanTagBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get plan tag bad request response has a 2xx status code
func (o *GetPlanTagBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan tag bad request response has a 3xx status code
func (o *GetPlanTagBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan tag bad request response has a 4xx status code
func (o *GetPlanTagBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plan tag bad request response has a 5xx status code
func (o *GetPlanTagBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan tag bad request response a status code equal to that given
func (o *GetPlanTagBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get plan tag bad request response
func (o *GetPlanTagBadRequest) Code() int {
	return 400
}

func (o *GetPlanTagBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagBadRequest %s", 400, payload)
}

func (o *GetPlanTagBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagBadRequest %s", 400, payload)
}

func (o *GetPlanTagBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetPlanTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPlanTagUnauthorized creates a GetPlanTagUnauthorized with default headers values
func NewGetPlanTagUnauthorized() *GetPlanTagUnauthorized {
	return &GetPlanTagUnauthorized{}
}

/*
GetPlanTagUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetPlanTagUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get plan tag unauthorized response has a 2xx status code
func (o *GetPlanTagUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan tag unauthorized response has a 3xx status code
func (o *GetPlanTagUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan tag unauthorized response has a 4xx status code
func (o *GetPlanTagUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plan tag unauthorized response has a 5xx status code
func (o *GetPlanTagUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan tag unauthorized response a status code equal to that given
func (o *GetPlanTagUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get plan tag unauthorized response
func (o *GetPlanTagUnauthorized) Code() int {
	return 401
}

func (o *GetPlanTagUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagUnauthorized %s", 401, payload)
}

func (o *GetPlanTagUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagUnauthorized %s", 401, payload)
}

func (o *GetPlanTagUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetPlanTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPlanTagNotFound creates a GetPlanTagNotFound with default headers values
func NewGetPlanTagNotFound() *GetPlanTagNotFound {
	return &GetPlanTagNotFound{}
}

/*
GetPlanTagNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetPlanTagNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get plan tag not found response has a 2xx status code
func (o *GetPlanTagNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan tag not found response has a 3xx status code
func (o *GetPlanTagNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan tag not found response has a 4xx status code
func (o *GetPlanTagNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plan tag not found response has a 5xx status code
func (o *GetPlanTagNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan tag not found response a status code equal to that given
func (o *GetPlanTagNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get plan tag not found response
func (o *GetPlanTagNotFound) Code() int {
	return 404
}

func (o *GetPlanTagNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagNotFound %s", 404, payload)
}

func (o *GetPlanTagNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagNotFound %s", 404, payload)
}

func (o *GetPlanTagNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetPlanTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPlanTagBadGateway creates a GetPlanTagBadGateway with default headers values
func NewGetPlanTagBadGateway() *GetPlanTagBadGateway {
	return &GetPlanTagBadGateway{}
}

/*
GetPlanTagBadGateway describes a response with status code 502, with default header values.

Bad Gateway
*/
type GetPlanTagBadGateway struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get plan tag bad gateway response has a 2xx status code
func (o *GetPlanTagBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan tag bad gateway response has a 3xx status code
func (o *GetPlanTagBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan tag bad gateway response has a 4xx status code
func (o *GetPlanTagBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plan tag bad gateway response has a 5xx status code
func (o *GetPlanTagBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this get plan tag bad gateway response a status code equal to that given
func (o *GetPlanTagBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the get plan tag bad gateway response
func (o *GetPlanTagBadGateway) Code() int {
	return 502
}

func (o *GetPlanTagBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagBadGateway %s", 502, payload)
}

func (o *GetPlanTagBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plan-tags/{planTagName}][%d] getPlanTagBadGateway %s", 502, payload)
}

func (o *GetPlanTagBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetPlanTagBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
