// Code generated by go-swagger; DO NOT EDIT.

package sandboxes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewApplySandboxParams creates a new ApplySandboxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplySandboxParams() *ApplySandboxParams {
	return &ApplySandboxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplySandboxParamsWithTimeout creates a new ApplySandboxParams object
// with the ability to set a timeout on a request.
func NewApplySandboxParamsWithTimeout(timeout time.Duration) *ApplySandboxParams {
	return &ApplySandboxParams{
		timeout: timeout,
	}
}

// NewApplySandboxParamsWithContext creates a new ApplySandboxParams object
// with the ability to set a context for a request.
func NewApplySandboxParamsWithContext(ctx context.Context) *ApplySandboxParams {
	return &ApplySandboxParams{
		Context: ctx,
	}
}

// NewApplySandboxParamsWithHTTPClient creates a new ApplySandboxParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplySandboxParamsWithHTTPClient(client *http.Client) *ApplySandboxParams {
	return &ApplySandboxParams{
		HTTPClient: client,
	}
}

/*
ApplySandboxParams contains all the parameters to send to the API endpoint

	for the apply sandbox operation.

	Typically these are written to a http.Request.
*/
type ApplySandboxParams struct {

	/* Data.

	   Request to create sandbox
	*/
	Data *models.Sandbox

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* SandboxName.

	   Sandbox Name
	*/
	SandboxName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apply sandbox params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplySandboxParams) WithDefaults() *ApplySandboxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apply sandbox params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplySandboxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apply sandbox params
func (o *ApplySandboxParams) WithTimeout(timeout time.Duration) *ApplySandboxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply sandbox params
func (o *ApplySandboxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply sandbox params
func (o *ApplySandboxParams) WithContext(ctx context.Context) *ApplySandboxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply sandbox params
func (o *ApplySandboxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply sandbox params
func (o *ApplySandboxParams) WithHTTPClient(client *http.Client) *ApplySandboxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply sandbox params
func (o *ApplySandboxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the apply sandbox params
func (o *ApplySandboxParams) WithData(data *models.Sandbox) *ApplySandboxParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the apply sandbox params
func (o *ApplySandboxParams) SetData(data *models.Sandbox) {
	o.Data = data
}

// WithOrgName adds the orgName to the apply sandbox params
func (o *ApplySandboxParams) WithOrgName(orgName string) *ApplySandboxParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the apply sandbox params
func (o *ApplySandboxParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithSandboxName adds the sandboxName to the apply sandbox params
func (o *ApplySandboxParams) WithSandboxName(sandboxName string) *ApplySandboxParams {
	o.SetSandboxName(sandboxName)
	return o
}

// SetSandboxName adds the sandboxName to the apply sandbox params
func (o *ApplySandboxParams) SetSandboxName(sandboxName string) {
	o.SandboxName = sandboxName
}

// WriteToRequest writes these params to a swagger request
func (o *ApplySandboxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param sandboxName
	if err := r.SetPathParam("sandboxName", o.SandboxName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
