// Code generated by go-swagger; DO NOT EDIT.

package sandboxes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// DeleteSandboxByIDReader is a Reader for the DeleteSandboxByID structure.
type DeleteSandboxByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSandboxByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSandboxByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteSandboxByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSandboxByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSandboxByIDOK creates a DeleteSandboxByIDOK with default headers values
func NewDeleteSandboxByIDOK() *DeleteSandboxByIDOK {
	return &DeleteSandboxByIDOK{}
}

/* DeleteSandboxByIDOK describes a response with status code 200, with default header values.

OK
*/
type DeleteSandboxByIDOK struct {
	Payload models.HandlerEmptyResponse
}

func (o *DeleteSandboxByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{orgName}/sandboxes/{sandboxID}][%d] deleteSandboxByIdOK  %+v", 200, o.Payload)
}
func (o *DeleteSandboxByIDOK) GetPayload() models.HandlerEmptyResponse {
	return o.Payload
}

func (o *DeleteSandboxByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSandboxByIDUnauthorized creates a DeleteSandboxByIDUnauthorized with default headers values
func NewDeleteSandboxByIDUnauthorized() *DeleteSandboxByIDUnauthorized {
	return &DeleteSandboxByIDUnauthorized{}
}

/* DeleteSandboxByIDUnauthorized describes a response with status code 401, with default header values.

Authorization failure
*/
type DeleteSandboxByIDUnauthorized struct {
}

func (o *DeleteSandboxByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{orgName}/sandboxes/{sandboxID}][%d] deleteSandboxByIdUnauthorized ", 401)
}

func (o *DeleteSandboxByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSandboxByIDInternalServerError creates a DeleteSandboxByIDInternalServerError with default headers values
func NewDeleteSandboxByIDInternalServerError() *DeleteSandboxByIDInternalServerError {
	return &DeleteSandboxByIDInternalServerError{}
}

/* DeleteSandboxByIDInternalServerError describes a response with status code 500, with default header values.

Internal server failure.
*/
type DeleteSandboxByIDInternalServerError struct {
}

func (o *DeleteSandboxByIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{orgName}/sandboxes/{sandboxID}][%d] deleteSandboxByIdInternalServerError ", 500)
}

func (o *DeleteSandboxByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
