// Code generated by go-swagger; DO NOT EDIT.

package sandboxes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// ExplainSandboxStatusContextReader is a Reader for the ExplainSandboxStatusContext structure.
type ExplainSandboxStatusContextReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExplainSandboxStatusContextReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewExplainSandboxStatusContextOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExplainSandboxStatusContextBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExplainSandboxStatusContextUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExplainSandboxStatusContextNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context] explain-sandbox-status-context", response, response.Code())
	}
}

// NewExplainSandboxStatusContextOK creates a ExplainSandboxStatusContextOK with default headers values
func NewExplainSandboxStatusContextOK() *ExplainSandboxStatusContextOK {
	return &ExplainSandboxStatusContextOK{}
}

/*
ExplainSandboxStatusContextOK describes a response with status code 200, with default header values.

OK
*/
type ExplainSandboxStatusContextOK struct {
	Payload *models.SandboxesExplainStatusContextResponse
}

// IsSuccess returns true when this explain sandbox status context o k response has a 2xx status code
func (o *ExplainSandboxStatusContextOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this explain sandbox status context o k response has a 3xx status code
func (o *ExplainSandboxStatusContextOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this explain sandbox status context o k response has a 4xx status code
func (o *ExplainSandboxStatusContextOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this explain sandbox status context o k response has a 5xx status code
func (o *ExplainSandboxStatusContextOK) IsServerError() bool {
	return false
}

// IsCode returns true when this explain sandbox status context o k response a status code equal to that given
func (o *ExplainSandboxStatusContextOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the explain sandbox status context o k response
func (o *ExplainSandboxStatusContextOK) Code() int {
	return 200
}

func (o *ExplainSandboxStatusContextOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextOK %s", 200, payload)
}

func (o *ExplainSandboxStatusContextOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextOK %s", 200, payload)
}

func (o *ExplainSandboxStatusContextOK) GetPayload() *models.SandboxesExplainStatusContextResponse {
	return o.Payload
}

func (o *ExplainSandboxStatusContextOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SandboxesExplainStatusContextResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExplainSandboxStatusContextBadRequest creates a ExplainSandboxStatusContextBadRequest with default headers values
func NewExplainSandboxStatusContextBadRequest() *ExplainSandboxStatusContextBadRequest {
	return &ExplainSandboxStatusContextBadRequest{}
}

/*
ExplainSandboxStatusContextBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ExplainSandboxStatusContextBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this explain sandbox status context bad request response has a 2xx status code
func (o *ExplainSandboxStatusContextBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this explain sandbox status context bad request response has a 3xx status code
func (o *ExplainSandboxStatusContextBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this explain sandbox status context bad request response has a 4xx status code
func (o *ExplainSandboxStatusContextBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this explain sandbox status context bad request response has a 5xx status code
func (o *ExplainSandboxStatusContextBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this explain sandbox status context bad request response a status code equal to that given
func (o *ExplainSandboxStatusContextBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the explain sandbox status context bad request response
func (o *ExplainSandboxStatusContextBadRequest) Code() int {
	return 400
}

func (o *ExplainSandboxStatusContextBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextBadRequest %s", 400, payload)
}

func (o *ExplainSandboxStatusContextBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextBadRequest %s", 400, payload)
}

func (o *ExplainSandboxStatusContextBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExplainSandboxStatusContextBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExplainSandboxStatusContextUnauthorized creates a ExplainSandboxStatusContextUnauthorized with default headers values
func NewExplainSandboxStatusContextUnauthorized() *ExplainSandboxStatusContextUnauthorized {
	return &ExplainSandboxStatusContextUnauthorized{}
}

/*
ExplainSandboxStatusContextUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ExplainSandboxStatusContextUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this explain sandbox status context unauthorized response has a 2xx status code
func (o *ExplainSandboxStatusContextUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this explain sandbox status context unauthorized response has a 3xx status code
func (o *ExplainSandboxStatusContextUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this explain sandbox status context unauthorized response has a 4xx status code
func (o *ExplainSandboxStatusContextUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this explain sandbox status context unauthorized response has a 5xx status code
func (o *ExplainSandboxStatusContextUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this explain sandbox status context unauthorized response a status code equal to that given
func (o *ExplainSandboxStatusContextUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the explain sandbox status context unauthorized response
func (o *ExplainSandboxStatusContextUnauthorized) Code() int {
	return 401
}

func (o *ExplainSandboxStatusContextUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextUnauthorized %s", 401, payload)
}

func (o *ExplainSandboxStatusContextUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextUnauthorized %s", 401, payload)
}

func (o *ExplainSandboxStatusContextUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExplainSandboxStatusContextUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewExplainSandboxStatusContextNotFound creates a ExplainSandboxStatusContextNotFound with default headers values
func NewExplainSandboxStatusContextNotFound() *ExplainSandboxStatusContextNotFound {
	return &ExplainSandboxStatusContextNotFound{}
}

/*
ExplainSandboxStatusContextNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ExplainSandboxStatusContextNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this explain sandbox status context not found response has a 2xx status code
func (o *ExplainSandboxStatusContextNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this explain sandbox status context not found response has a 3xx status code
func (o *ExplainSandboxStatusContextNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this explain sandbox status context not found response has a 4xx status code
func (o *ExplainSandboxStatusContextNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this explain sandbox status context not found response has a 5xx status code
func (o *ExplainSandboxStatusContextNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this explain sandbox status context not found response a status code equal to that given
func (o *ExplainSandboxStatusContextNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the explain sandbox status context not found response
func (o *ExplainSandboxStatusContextNotFound) Code() int {
	return 404
}

func (o *ExplainSandboxStatusContextNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextNotFound %s", 404, payload)
}

func (o *ExplainSandboxStatusContextNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/sandboxes/{sandboxName}/explain-status/context][%d] explainSandboxStatusContextNotFound %s", 404, payload)
}

func (o *ExplainSandboxStatusContextNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ExplainSandboxStatusContextNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
