// Code generated by go-swagger; DO NOT EDIT.

package tests

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTestParams creates a new GetTestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTestParams() *GetTestParams {
	return NewGetTestParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetTestParamsWithTimeout creates a new GetTestParams object
// with the ability to set a timeout on a request.
func NewGetTestParamsWithTimeout(timeout time.Duration) *GetTestParams {
	return &GetTestParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetTestParamsWithContext creates a new GetTestParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetTestParams].
func NewGetTestParamsWithContext(ctx context.Context) *GetTestParams {
	return &GetTestParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetTestParamsWithHTTPClient creates a new GetTestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTestParamsWithHTTPClient(client *http.Client) *GetTestParams {
	return &GetTestParams{
		HTTPClient: client,
	}
}

/*
GetTestParams contains all the parameters to send to the API endpoint

	for the get test operation.

	Typically these are written to a http.Request.
*/
type GetTestParams struct {

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* TestName.

	   Test Name
	*/
	TestName string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestParams) WithDefaults() *GetTestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get test params.
func (o *GetTestParams) WithTimeout(timeout time.Duration) *GetTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test params.
func (o *GetTestParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get test params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetTestParams].
func (o *GetTestParams) WithContext(ctx context.Context) *GetTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetTestParams].
func (o *GetTestParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get test params.
func (o *GetTestParams) WithHTTPClient(client *http.Client) *GetTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test params.
func (o *GetTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgName adds the orgName to the get test params.
func (o *GetTestParams) WithOrgName(orgName string) *GetTestParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the get test params.
func (o *GetTestParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithTestName adds the testName to the get test params.
func (o *GetTestParams) WithTestName(testName string) *GetTestParams {
	o.SetTestName(testName)
	return o
}

// SetTestName adds the testName to the get test params.
func (o *GetTestParams) SetTestName(testName string) {
	o.TestName = testName
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param testName
	if err := r.SetPathParam("testName", o.TestName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
