// Code generated by go-swagger; DO NOT EDIT.

package skill_runner_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSkillrunnergroupParams creates a new GetSkillrunnergroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSkillrunnergroupParams() *GetSkillrunnergroupParams {
	return &GetSkillrunnergroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSkillrunnergroupParamsWithTimeout creates a new GetSkillrunnergroupParams object
// with the ability to set a timeout on a request.
func NewGetSkillrunnergroupParamsWithTimeout(timeout time.Duration) *GetSkillrunnergroupParams {
	return &GetSkillrunnergroupParams{
		timeout: timeout,
	}
}

// NewGetSkillrunnergroupParamsWithContext creates a new GetSkillrunnergroupParams object
// with the ability to set a context for a request.
func NewGetSkillrunnergroupParamsWithContext(ctx context.Context) *GetSkillrunnergroupParams {
	return &GetSkillrunnergroupParams{
		Context: ctx,
	}
}

// NewGetSkillrunnergroupParamsWithHTTPClient creates a new GetSkillrunnergroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSkillrunnergroupParamsWithHTTPClient(client *http.Client) *GetSkillrunnergroupParams {
	return &GetSkillrunnergroupParams{
		HTTPClient: client,
	}
}

/*
GetSkillrunnergroupParams contains all the parameters to send to the API endpoint

	for the get skillrunnergroup operation.

	Typically these are written to a http.Request.
*/
type GetSkillrunnergroupParams struct {

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* SkillRunnerGroupName.

	   SkillRunnerGroup Name
	*/
	SkillRunnerGroupName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get skillrunnergroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSkillrunnergroupParams) WithDefaults() *GetSkillrunnergroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get skillrunnergroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSkillrunnergroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) WithTimeout(timeout time.Duration) *GetSkillrunnergroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) WithContext(ctx context.Context) *GetSkillrunnergroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) WithHTTPClient(client *http.Client) *GetSkillrunnergroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgName adds the orgName to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) WithOrgName(orgName string) *GetSkillrunnergroupParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithSkillRunnerGroupName adds the skillRunnerGroupName to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) WithSkillRunnerGroupName(skillRunnerGroupName string) *GetSkillrunnergroupParams {
	o.SetSkillRunnerGroupName(skillRunnerGroupName)
	return o
}

// SetSkillRunnerGroupName adds the skillRunnerGroupName to the get skillrunnergroup params
func (o *GetSkillrunnergroupParams) SetSkillRunnerGroupName(skillRunnerGroupName string) {
	o.SkillRunnerGroupName = skillRunnerGroupName
}

// WriteToRequest writes these params to a swagger request
func (o *GetSkillrunnergroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param skillRunnerGroupName
	if err := r.SetPathParam("skillRunnerGroupName", o.SkillRunnerGroupName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
