// Code generated by go-swagger; DO NOT EDIT.

package artifacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInfoJobAttemptArtifactParams creates a new InfoJobAttemptArtifactParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInfoJobAttemptArtifactParams() *InfoJobAttemptArtifactParams {
	return &InfoJobAttemptArtifactParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInfoJobAttemptArtifactParamsWithTimeout creates a new InfoJobAttemptArtifactParams object
// with the ability to set a timeout on a request.
func NewInfoJobAttemptArtifactParamsWithTimeout(timeout time.Duration) *InfoJobAttemptArtifactParams {
	return &InfoJobAttemptArtifactParams{
		timeout: timeout,
	}
}

// NewInfoJobAttemptArtifactParamsWithContext creates a new InfoJobAttemptArtifactParams object
// with the ability to set a context for a request.
func NewInfoJobAttemptArtifactParamsWithContext(ctx context.Context) *InfoJobAttemptArtifactParams {
	return &InfoJobAttemptArtifactParams{
		Context: ctx,
	}
}

// NewInfoJobAttemptArtifactParamsWithHTTPClient creates a new InfoJobAttemptArtifactParams object
// with the ability to set a custom HTTPClient for a request.
func NewInfoJobAttemptArtifactParamsWithHTTPClient(client *http.Client) *InfoJobAttemptArtifactParams {
	return &InfoJobAttemptArtifactParams{
		HTTPClient: client,
	}
}

/*
InfoJobAttemptArtifactParams contains all the parameters to send to the API endpoint

	for the info job attempt artifact operation.

	Typically these are written to a http.Request.
*/
type InfoJobAttemptArtifactParams struct {

	/* JobAttempt.

	   Job Attempt ID
	*/
	JobAttempt string

	/* JobName.

	   Job Name
	*/
	JobName string

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* Path.

	   Artifact Path
	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the info job attempt artifact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InfoJobAttemptArtifactParams) WithDefaults() *InfoJobAttemptArtifactParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the info job attempt artifact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InfoJobAttemptArtifactParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithTimeout(timeout time.Duration) *InfoJobAttemptArtifactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithContext(ctx context.Context) *InfoJobAttemptArtifactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithHTTPClient(client *http.Client) *InfoJobAttemptArtifactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobAttempt adds the jobAttempt to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithJobAttempt(jobAttempt string) *InfoJobAttemptArtifactParams {
	o.SetJobAttempt(jobAttempt)
	return o
}

// SetJobAttempt adds the jobAttempt to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetJobAttempt(jobAttempt string) {
	o.JobAttempt = jobAttempt
}

// WithJobName adds the jobName to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithJobName(jobName string) *InfoJobAttemptArtifactParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WithOrgName adds the orgName to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithOrgName(orgName string) *InfoJobAttemptArtifactParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithPath adds the path to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) WithPath(path string) *InfoJobAttemptArtifactParams {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the info job attempt artifact params
func (o *InfoJobAttemptArtifactParams) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *InfoJobAttemptArtifactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param jobAttempt
	if err := r.SetPathParam("jobAttempt", o.JobAttempt); err != nil {
		return err
	}

	// path param jobName
	if err := r.SetPathParam("jobName", o.JobName); err != nil {
		return err
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// query param path
	qrPath := o.Path
	qPath := qrPath
	if qPath != "" {

		if err := r.SetQueryParam("path", qPath); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
