/*
Signadot API

API for Signadot Sandboxes

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CustomPatch struct for CustomPatch
type CustomPatch struct {
	Type *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewCustomPatch instantiates a new CustomPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomPatch() *CustomPatch {
	this := CustomPatch{}
	return &this
}

// NewCustomPatchWithDefaults instantiates a new CustomPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomPatchWithDefaults() *CustomPatch {
	this := CustomPatch{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CustomPatch) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPatch) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CustomPatch) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CustomPatch) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CustomPatch) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomPatch) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CustomPatch) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CustomPatch) SetValue(v string) {
	o.Value = &v
}

func (o CustomPatch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCustomPatch struct {
	value *CustomPatch
	isSet bool
}

func (v NullableCustomPatch) Get() *CustomPatch {
	return v.value
}

func (v *NullableCustomPatch) Set(val *CustomPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomPatch(val *CustomPatch) *NullableCustomPatch {
	return &NullableCustomPatch{value: val, isSet: true}
}

func (v NullableCustomPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


