// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewAuthDeviceGetTokenParams creates a new AuthDeviceGetTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthDeviceGetTokenParams() *AuthDeviceGetTokenParams {
	return &AuthDeviceGetTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthDeviceGetTokenParamsWithTimeout creates a new AuthDeviceGetTokenParams object
// with the ability to set a timeout on a request.
func NewAuthDeviceGetTokenParamsWithTimeout(timeout time.Duration) *AuthDeviceGetTokenParams {
	return &AuthDeviceGetTokenParams{
		timeout: timeout,
	}
}

// NewAuthDeviceGetTokenParamsWithContext creates a new AuthDeviceGetTokenParams object
// with the ability to set a context for a request.
func NewAuthDeviceGetTokenParamsWithContext(ctx context.Context) *AuthDeviceGetTokenParams {
	return &AuthDeviceGetTokenParams{
		Context: ctx,
	}
}

// NewAuthDeviceGetTokenParamsWithHTTPClient creates a new AuthDeviceGetTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthDeviceGetTokenParamsWithHTTPClient(client *http.Client) *AuthDeviceGetTokenParams {
	return &AuthDeviceGetTokenParams{
		HTTPClient: client,
	}
}

/*
AuthDeviceGetTokenParams contains all the parameters to send to the API endpoint

	for the auth device get token operation.

	Typically these are written to a http.Request.
*/
type AuthDeviceGetTokenParams struct {

	/* Data.

	   Information to get the token
	*/
	Data *models.AuthdevicesTokenInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth device get token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthDeviceGetTokenParams) WithDefaults() *AuthDeviceGetTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth device get token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthDeviceGetTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth device get token params
func (o *AuthDeviceGetTokenParams) WithTimeout(timeout time.Duration) *AuthDeviceGetTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth device get token params
func (o *AuthDeviceGetTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth device get token params
func (o *AuthDeviceGetTokenParams) WithContext(ctx context.Context) *AuthDeviceGetTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth device get token params
func (o *AuthDeviceGetTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth device get token params
func (o *AuthDeviceGetTokenParams) WithHTTPClient(client *http.Client) *AuthDeviceGetTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth device get token params
func (o *AuthDeviceGetTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the auth device get token params
func (o *AuthDeviceGetTokenParams) WithData(data *models.AuthdevicesTokenInput) *AuthDeviceGetTokenParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the auth device get token params
func (o *AuthDeviceGetTokenParams) SetData(data *models.AuthdevicesTokenInput) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *AuthDeviceGetTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
