// Code generated by go-swagger; DO NOT EDIT.

package test_executions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewCreateTestExecutionForTestParams creates a new CreateTestExecutionForTestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateTestExecutionForTestParams() *CreateTestExecutionForTestParams {
	return &CreateTestExecutionForTestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTestExecutionForTestParamsWithTimeout creates a new CreateTestExecutionForTestParams object
// with the ability to set a timeout on a request.
func NewCreateTestExecutionForTestParamsWithTimeout(timeout time.Duration) *CreateTestExecutionForTestParams {
	return &CreateTestExecutionForTestParams{
		timeout: timeout,
	}
}

// NewCreateTestExecutionForTestParamsWithContext creates a new CreateTestExecutionForTestParams object
// with the ability to set a context for a request.
func NewCreateTestExecutionForTestParamsWithContext(ctx context.Context) *CreateTestExecutionForTestParams {
	return &CreateTestExecutionForTestParams{
		Context: ctx,
	}
}

// NewCreateTestExecutionForTestParamsWithHTTPClient creates a new CreateTestExecutionForTestParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateTestExecutionForTestParamsWithHTTPClient(client *http.Client) *CreateTestExecutionForTestParams {
	return &CreateTestExecutionForTestParams{
		HTTPClient: client,
	}
}

/*
CreateTestExecutionForTestParams contains all the parameters to send to the API endpoint

	for the create test execution for test operation.

	Typically these are written to a http.Request.
*/
type CreateTestExecutionForTestParams struct {

	/* Data.

	   Request to create a test execution
	*/
	Data *models.TestExecutionSpec

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* TestName.

	   Test name
	*/
	TestName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create test execution for test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTestExecutionForTestParams) WithDefaults() *CreateTestExecutionForTestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create test execution for test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTestExecutionForTestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithTimeout(timeout time.Duration) *CreateTestExecutionForTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithContext(ctx context.Context) *CreateTestExecutionForTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithHTTPClient(client *http.Client) *CreateTestExecutionForTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithData(data *models.TestExecutionSpec) *CreateTestExecutionForTestParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetData(data *models.TestExecutionSpec) {
	o.Data = data
}

// WithOrgName adds the orgName to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithOrgName(orgName string) *CreateTestExecutionForTestParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithTestName adds the testName to the create test execution for test params
func (o *CreateTestExecutionForTestParams) WithTestName(testName string) *CreateTestExecutionForTestParams {
	o.SetTestName(testName)
	return o
}

// SetTestName adds the testName to the create test execution for test params
func (o *CreateTestExecutionForTestParams) SetTestName(testName string) {
	o.TestName = testName
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTestExecutionForTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param testName
	if err := r.SetPathParam("testName", o.TestName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
