// Code generated by go-swagger; DO NOT EDIT.

package plan_runner_groups

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewApplyPlanrunnergroupParams creates a new ApplyPlanrunnergroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplyPlanrunnergroupParams() *ApplyPlanrunnergroupParams {
	return &ApplyPlanrunnergroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplyPlanrunnergroupParamsWithTimeout creates a new ApplyPlanrunnergroupParams object
// with the ability to set a timeout on a request.
func NewApplyPlanrunnergroupParamsWithTimeout(timeout time.Duration) *ApplyPlanrunnergroupParams {
	return &ApplyPlanrunnergroupParams{
		timeout: timeout,
	}
}

// NewApplyPlanrunnergroupParamsWithContext creates a new ApplyPlanrunnergroupParams object
// with the ability to set a context for a request.
func NewApplyPlanrunnergroupParamsWithContext(ctx context.Context) *ApplyPlanrunnergroupParams {
	return &ApplyPlanrunnergroupParams{
		Context: ctx,
	}
}

// NewApplyPlanrunnergroupParamsWithHTTPClient creates a new ApplyPlanrunnergroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplyPlanrunnergroupParamsWithHTTPClient(client *http.Client) *ApplyPlanrunnergroupParams {
	return &ApplyPlanrunnergroupParams{
		HTTPClient: client,
	}
}

/*
ApplyPlanrunnergroupParams contains all the parameters to send to the API endpoint

	for the apply planrunnergroup operation.

	Typically these are written to a http.Request.
*/
type ApplyPlanrunnergroupParams struct {

	/* Data.

	   Request to create or update plan runner group
	*/
	Data *models.PlanRunnerGroup

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* PlanRunnerGroupName.

	   PlanRunnerGroup Name
	*/
	PlanRunnerGroupName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apply planrunnergroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyPlanrunnergroupParams) WithDefaults() *ApplyPlanrunnergroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apply planrunnergroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyPlanrunnergroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithTimeout(timeout time.Duration) *ApplyPlanrunnergroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithContext(ctx context.Context) *ApplyPlanrunnergroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithHTTPClient(client *http.Client) *ApplyPlanrunnergroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithData(data *models.PlanRunnerGroup) *ApplyPlanrunnergroupParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetData(data *models.PlanRunnerGroup) {
	o.Data = data
}

// WithOrgName adds the orgName to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithOrgName(orgName string) *ApplyPlanrunnergroupParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithPlanRunnerGroupName adds the planRunnerGroupName to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) WithPlanRunnerGroupName(planRunnerGroupName string) *ApplyPlanrunnergroupParams {
	o.SetPlanRunnerGroupName(planRunnerGroupName)
	return o
}

// SetPlanRunnerGroupName adds the planRunnerGroupName to the apply planrunnergroup params
func (o *ApplyPlanrunnergroupParams) SetPlanRunnerGroupName(planRunnerGroupName string) {
	o.PlanRunnerGroupName = planRunnerGroupName
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyPlanrunnergroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param planRunnerGroupName
	if err := r.SetPathParam("planRunnerGroupName", o.PlanRunnerGroupName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
