// Code generated by go-swagger; DO NOT EDIT.

package plan_runner_groups

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// UploadPrgImageReader is a Reader for the UploadPrgImage structure.
type UploadPrgImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadPrgImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUploadPrgImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUploadPrgImageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUploadPrgImageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewUploadPrgImageBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/] upload-prg-image", response, response.Code())
	}
}

// NewUploadPrgImageOK creates a UploadPrgImageOK with default headers values
func NewUploadPrgImageOK() *UploadPrgImageOK {
	return &UploadPrgImageOK{}
}

/*
UploadPrgImageOK describes a response with status code 200, with default header values.

OK
*/
type UploadPrgImageOK struct {
	Payload any
}

// IsSuccess returns true when this upload prg image o k response has a 2xx status code
func (o *UploadPrgImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload prg image o k response has a 3xx status code
func (o *UploadPrgImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload prg image o k response has a 4xx status code
func (o *UploadPrgImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload prg image o k response has a 5xx status code
func (o *UploadPrgImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload prg image o k response a status code equal to that given
func (o *UploadPrgImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload prg image o k response
func (o *UploadPrgImageOK) Code() int {
	return 200
}

func (o *UploadPrgImageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageOK %s", 200, payload)
}

func (o *UploadPrgImageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageOK %s", 200, payload)
}

func (o *UploadPrgImageOK) GetPayload() any {
	return o.Payload
}

func (o *UploadPrgImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadPrgImageBadRequest creates a UploadPrgImageBadRequest with default headers values
func NewUploadPrgImageBadRequest() *UploadPrgImageBadRequest {
	return &UploadPrgImageBadRequest{}
}

/*
UploadPrgImageBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UploadPrgImageBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload prg image bad request response has a 2xx status code
func (o *UploadPrgImageBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload prg image bad request response has a 3xx status code
func (o *UploadPrgImageBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload prg image bad request response has a 4xx status code
func (o *UploadPrgImageBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload prg image bad request response has a 5xx status code
func (o *UploadPrgImageBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this upload prg image bad request response a status code equal to that given
func (o *UploadPrgImageBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the upload prg image bad request response
func (o *UploadPrgImageBadRequest) Code() int {
	return 400
}

func (o *UploadPrgImageBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageBadRequest %s", 400, payload)
}

func (o *UploadPrgImageBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageBadRequest %s", 400, payload)
}

func (o *UploadPrgImageBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadPrgImageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadPrgImageUnauthorized creates a UploadPrgImageUnauthorized with default headers values
func NewUploadPrgImageUnauthorized() *UploadPrgImageUnauthorized {
	return &UploadPrgImageUnauthorized{}
}

/*
UploadPrgImageUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UploadPrgImageUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload prg image unauthorized response has a 2xx status code
func (o *UploadPrgImageUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload prg image unauthorized response has a 3xx status code
func (o *UploadPrgImageUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload prg image unauthorized response has a 4xx status code
func (o *UploadPrgImageUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this upload prg image unauthorized response has a 5xx status code
func (o *UploadPrgImageUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this upload prg image unauthorized response a status code equal to that given
func (o *UploadPrgImageUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the upload prg image unauthorized response
func (o *UploadPrgImageUnauthorized) Code() int {
	return 401
}

func (o *UploadPrgImageUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageUnauthorized %s", 401, payload)
}

func (o *UploadPrgImageUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageUnauthorized %s", 401, payload)
}

func (o *UploadPrgImageUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadPrgImageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUploadPrgImageBadGateway creates a UploadPrgImageBadGateway with default headers values
func NewUploadPrgImageBadGateway() *UploadPrgImageBadGateway {
	return &UploadPrgImageBadGateway{}
}

/*
UploadPrgImageBadGateway describes a response with status code 502, with default header values.

Bad Gateway
*/
type UploadPrgImageBadGateway struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this upload prg image bad gateway response has a 2xx status code
func (o *UploadPrgImageBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload prg image bad gateway response has a 3xx status code
func (o *UploadPrgImageBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload prg image bad gateway response has a 4xx status code
func (o *UploadPrgImageBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload prg image bad gateway response has a 5xx status code
func (o *UploadPrgImageBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this upload prg image bad gateway response a status code equal to that given
func (o *UploadPrgImageBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the upload prg image bad gateway response
func (o *UploadPrgImageBadGateway) Code() int {
	return 502
}

func (o *UploadPrgImageBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageBadGateway %s", 502, payload)
}

func (o *UploadPrgImageBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plan-runnergroups/{planRunnerGroupName}/images/][%d] uploadPrgImageBadGateway %s", 502, payload)
}

func (o *UploadPrgImageBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *UploadPrgImageBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
