// Code generated by go-swagger; DO NOT EDIT.

package plans

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// CompilePlanReader is a Reader for the CompilePlan structure.
type CompilePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompilePlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCompilePlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCompilePlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCompilePlanUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewCompilePlanBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /orgs/{orgName}/plans/compile] compile-plan", response, response.Code())
	}
}

// NewCompilePlanOK creates a CompilePlanOK with default headers values
func NewCompilePlanOK() *CompilePlanOK {
	return &CompilePlanOK{}
}

/*
CompilePlanOK describes a response with status code 200, with default header values.

OK
*/
type CompilePlanOK struct {
	Payload *models.RunnablePlan
}

// IsSuccess returns true when this compile plan o k response has a 2xx status code
func (o *CompilePlanOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this compile plan o k response has a 3xx status code
func (o *CompilePlanOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this compile plan o k response has a 4xx status code
func (o *CompilePlanOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this compile plan o k response has a 5xx status code
func (o *CompilePlanOK) IsServerError() bool {
	return false
}

// IsCode returns true when this compile plan o k response a status code equal to that given
func (o *CompilePlanOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the compile plan o k response
func (o *CompilePlanOK) Code() int {
	return 200
}

func (o *CompilePlanOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanOK %s", 200, payload)
}

func (o *CompilePlanOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanOK %s", 200, payload)
}

func (o *CompilePlanOK) GetPayload() *models.RunnablePlan {
	return o.Payload
}

func (o *CompilePlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunnablePlan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCompilePlanBadRequest creates a CompilePlanBadRequest with default headers values
func NewCompilePlanBadRequest() *CompilePlanBadRequest {
	return &CompilePlanBadRequest{}
}

/*
CompilePlanBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CompilePlanBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this compile plan bad request response has a 2xx status code
func (o *CompilePlanBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this compile plan bad request response has a 3xx status code
func (o *CompilePlanBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this compile plan bad request response has a 4xx status code
func (o *CompilePlanBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this compile plan bad request response has a 5xx status code
func (o *CompilePlanBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this compile plan bad request response a status code equal to that given
func (o *CompilePlanBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the compile plan bad request response
func (o *CompilePlanBadRequest) Code() int {
	return 400
}

func (o *CompilePlanBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanBadRequest %s", 400, payload)
}

func (o *CompilePlanBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanBadRequest %s", 400, payload)
}

func (o *CompilePlanBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CompilePlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCompilePlanUnauthorized creates a CompilePlanUnauthorized with default headers values
func NewCompilePlanUnauthorized() *CompilePlanUnauthorized {
	return &CompilePlanUnauthorized{}
}

/*
CompilePlanUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CompilePlanUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this compile plan unauthorized response has a 2xx status code
func (o *CompilePlanUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this compile plan unauthorized response has a 3xx status code
func (o *CompilePlanUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this compile plan unauthorized response has a 4xx status code
func (o *CompilePlanUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this compile plan unauthorized response has a 5xx status code
func (o *CompilePlanUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this compile plan unauthorized response a status code equal to that given
func (o *CompilePlanUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the compile plan unauthorized response
func (o *CompilePlanUnauthorized) Code() int {
	return 401
}

func (o *CompilePlanUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanUnauthorized %s", 401, payload)
}

func (o *CompilePlanUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanUnauthorized %s", 401, payload)
}

func (o *CompilePlanUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CompilePlanUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCompilePlanBadGateway creates a CompilePlanBadGateway with default headers values
func NewCompilePlanBadGateway() *CompilePlanBadGateway {
	return &CompilePlanBadGateway{}
}

/*
CompilePlanBadGateway describes a response with status code 502, with default header values.

Bad Gateway
*/
type CompilePlanBadGateway struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this compile plan bad gateway response has a 2xx status code
func (o *CompilePlanBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this compile plan bad gateway response has a 3xx status code
func (o *CompilePlanBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this compile plan bad gateway response has a 4xx status code
func (o *CompilePlanBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this compile plan bad gateway response has a 5xx status code
func (o *CompilePlanBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this compile plan bad gateway response a status code equal to that given
func (o *CompilePlanBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the compile plan bad gateway response
func (o *CompilePlanBadGateway) Code() int {
	return 502
}

func (o *CompilePlanBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanBadGateway %s", 502, payload)
}

func (o *CompilePlanBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /orgs/{orgName}/plans/compile][%d] compilePlanBadGateway %s", 502, payload)
}

func (o *CompilePlanBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CompilePlanBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
