// Code generated by go-swagger; DO NOT EDIT.

package plans

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlanParams creates a new GetPlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlanParams() *GetPlanParams {
	return &GetPlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlanParamsWithTimeout creates a new GetPlanParams object
// with the ability to set a timeout on a request.
func NewGetPlanParamsWithTimeout(timeout time.Duration) *GetPlanParams {
	return &GetPlanParams{
		timeout: timeout,
	}
}

// NewGetPlanParamsWithContext creates a new GetPlanParams object
// with the ability to set a context for a request.
func NewGetPlanParamsWithContext(ctx context.Context) *GetPlanParams {
	return &GetPlanParams{
		Context: ctx,
	}
}

// NewGetPlanParamsWithHTTPClient creates a new GetPlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlanParamsWithHTTPClient(client *http.Client) *GetPlanParams {
	return &GetPlanParams{
		HTTPClient: client,
	}
}

/*
GetPlanParams contains all the parameters to send to the API endpoint

	for the get plan operation.

	Typically these are written to a http.Request.
*/
type GetPlanParams struct {

	/* Expand.

	   Set to 'action' to include each step's full action contents (body, schemas, extraInputsSchemaPolicy). Default returns the compact by-ref form.
	*/
	Expand *string

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* PlanID.

	   Plan ID
	*/
	PlanID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanParams) WithDefaults() *GetPlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plan params
func (o *GetPlanParams) WithTimeout(timeout time.Duration) *GetPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plan params
func (o *GetPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plan params
func (o *GetPlanParams) WithContext(ctx context.Context) *GetPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plan params
func (o *GetPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plan params
func (o *GetPlanParams) WithHTTPClient(client *http.Client) *GetPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plan params
func (o *GetPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExpand adds the expand to the get plan params
func (o *GetPlanParams) WithExpand(expand *string) *GetPlanParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the get plan params
func (o *GetPlanParams) SetExpand(expand *string) {
	o.Expand = expand
}

// WithOrgName adds the orgName to the get plan params
func (o *GetPlanParams) WithOrgName(orgName string) *GetPlanParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the get plan params
func (o *GetPlanParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithPlanID adds the planID to the get plan params
func (o *GetPlanParams) WithPlanID(planID string) *GetPlanParams {
	o.SetPlanID(planID)
	return o
}

// SetPlanID adds the planId to the get plan params
func (o *GetPlanParams) SetPlanID(planID string) {
	o.PlanID = planID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Expand != nil {

		// query param expand
		var qrExpand string

		if o.Expand != nil {
			qrExpand = *o.Expand
		}
		qExpand := qrExpand
		if qExpand != "" {

			if err := r.SetQueryParam("expand", qExpand); err != nil {
				return err
			}
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param planID
	if err := r.SetPathParam("planID", o.PlanID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
