// Code generated by go-swagger; DO NOT EDIT.

package plans

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// ListPlansReader is a Reader for the ListPlans structure.
type ListPlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListPlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListPlansBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListPlansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewListPlansBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{orgName}/plans] list-plans", response, response.Code())
	}
}

// NewListPlansOK creates a ListPlansOK with default headers values
func NewListPlansOK() *ListPlansOK {
	return &ListPlansOK{}
}

/*
ListPlansOK describes a response with status code 200, with default header values.

OK
*/
type ListPlansOK struct {
	Payload []*models.RunnablePlan
}

// IsSuccess returns true when this list plans o k response has a 2xx status code
func (o *ListPlansOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list plans o k response has a 3xx status code
func (o *ListPlansOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list plans o k response has a 4xx status code
func (o *ListPlansOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list plans o k response has a 5xx status code
func (o *ListPlansOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list plans o k response a status code equal to that given
func (o *ListPlansOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list plans o k response
func (o *ListPlansOK) Code() int {
	return 200
}

func (o *ListPlansOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansOK %s", 200, payload)
}

func (o *ListPlansOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansOK %s", 200, payload)
}

func (o *ListPlansOK) GetPayload() []*models.RunnablePlan {
	return o.Payload
}

func (o *ListPlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPlansBadRequest creates a ListPlansBadRequest with default headers values
func NewListPlansBadRequest() *ListPlansBadRequest {
	return &ListPlansBadRequest{}
}

/*
ListPlansBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ListPlansBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list plans bad request response has a 2xx status code
func (o *ListPlansBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list plans bad request response has a 3xx status code
func (o *ListPlansBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list plans bad request response has a 4xx status code
func (o *ListPlansBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list plans bad request response has a 5xx status code
func (o *ListPlansBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list plans bad request response a status code equal to that given
func (o *ListPlansBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list plans bad request response
func (o *ListPlansBadRequest) Code() int {
	return 400
}

func (o *ListPlansBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansBadRequest %s", 400, payload)
}

func (o *ListPlansBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansBadRequest %s", 400, payload)
}

func (o *ListPlansBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListPlansBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPlansUnauthorized creates a ListPlansUnauthorized with default headers values
func NewListPlansUnauthorized() *ListPlansUnauthorized {
	return &ListPlansUnauthorized{}
}

/*
ListPlansUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListPlansUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list plans unauthorized response has a 2xx status code
func (o *ListPlansUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list plans unauthorized response has a 3xx status code
func (o *ListPlansUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list plans unauthorized response has a 4xx status code
func (o *ListPlansUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list plans unauthorized response has a 5xx status code
func (o *ListPlansUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list plans unauthorized response a status code equal to that given
func (o *ListPlansUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list plans unauthorized response
func (o *ListPlansUnauthorized) Code() int {
	return 401
}

func (o *ListPlansUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansUnauthorized %s", 401, payload)
}

func (o *ListPlansUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansUnauthorized %s", 401, payload)
}

func (o *ListPlansUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListPlansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListPlansBadGateway creates a ListPlansBadGateway with default headers values
func NewListPlansBadGateway() *ListPlansBadGateway {
	return &ListPlansBadGateway{}
}

/*
ListPlansBadGateway describes a response with status code 502, with default header values.

Bad Gateway
*/
type ListPlansBadGateway struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list plans bad gateway response has a 2xx status code
func (o *ListPlansBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list plans bad gateway response has a 3xx status code
func (o *ListPlansBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list plans bad gateway response has a 4xx status code
func (o *ListPlansBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this list plans bad gateway response has a 5xx status code
func (o *ListPlansBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this list plans bad gateway response a status code equal to that given
func (o *ListPlansBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the list plans bad gateway response
func (o *ListPlansBadGateway) Code() int {
	return 502
}

func (o *ListPlansBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansBadGateway %s", 502, payload)
}

func (o *ListPlansBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/plans][%d] listPlansBadGateway %s", 502, payload)
}

func (o *ListPlansBadGateway) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListPlansBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
