// Code generated by go-swagger; DO NOT EDIT.

package settings

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrgsOrgNameSettingsAiParams creates a new GetOrgsOrgNameSettingsAiParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrgsOrgNameSettingsAiParams() *GetOrgsOrgNameSettingsAiParams {
	return &GetOrgsOrgNameSettingsAiParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgsOrgNameSettingsAiParamsWithTimeout creates a new GetOrgsOrgNameSettingsAiParams object
// with the ability to set a timeout on a request.
func NewGetOrgsOrgNameSettingsAiParamsWithTimeout(timeout time.Duration) *GetOrgsOrgNameSettingsAiParams {
	return &GetOrgsOrgNameSettingsAiParams{
		timeout: timeout,
	}
}

// NewGetOrgsOrgNameSettingsAiParamsWithContext creates a new GetOrgsOrgNameSettingsAiParams object
// with the ability to set a context for a request.
func NewGetOrgsOrgNameSettingsAiParamsWithContext(ctx context.Context) *GetOrgsOrgNameSettingsAiParams {
	return &GetOrgsOrgNameSettingsAiParams{
		Context: ctx,
	}
}

// NewGetOrgsOrgNameSettingsAiParamsWithHTTPClient creates a new GetOrgsOrgNameSettingsAiParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrgsOrgNameSettingsAiParamsWithHTTPClient(client *http.Client) *GetOrgsOrgNameSettingsAiParams {
	return &GetOrgsOrgNameSettingsAiParams{
		HTTPClient: client,
	}
}

/*
GetOrgsOrgNameSettingsAiParams contains all the parameters to send to the API endpoint

	for the get orgs org name settings ai operation.

	Typically these are written to a http.Request.
*/
type GetOrgsOrgNameSettingsAiParams struct {

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get orgs org name settings ai params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgsOrgNameSettingsAiParams) WithDefaults() *GetOrgsOrgNameSettingsAiParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get orgs org name settings ai params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgsOrgNameSettingsAiParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) WithTimeout(timeout time.Duration) *GetOrgsOrgNameSettingsAiParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) WithContext(ctx context.Context) *GetOrgsOrgNameSettingsAiParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) WithHTTPClient(client *http.Client) *GetOrgsOrgNameSettingsAiParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgName adds the orgName to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) WithOrgName(orgName string) *GetOrgsOrgNameSettingsAiParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the get orgs org name settings ai params
func (o *GetOrgsOrgNameSettingsAiParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgsOrgNameSettingsAiParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
