// Code generated by go-swagger; DO NOT EDIT.

package settings

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// GetOrgsOrgNameSettingsAiReader is a Reader for the GetOrgsOrgNameSettingsAi structure.
type GetOrgsOrgNameSettingsAiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrgsOrgNameSettingsAiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrgsOrgNameSettingsAiOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetOrgsOrgNameSettingsAiUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrgsOrgNameSettingsAiNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orgs/{orgName}/settings/ai] GetOrgsOrgNameSettingsAi", response, response.Code())
	}
}

// NewGetOrgsOrgNameSettingsAiOK creates a GetOrgsOrgNameSettingsAiOK with default headers values
func NewGetOrgsOrgNameSettingsAiOK() *GetOrgsOrgNameSettingsAiOK {
	return &GetOrgsOrgNameSettingsAiOK{}
}

/*
GetOrgsOrgNameSettingsAiOK describes a response with status code 200, with default header values.

OK
*/
type GetOrgsOrgNameSettingsAiOK struct {
	Payload *models.SettingsAISettings
}

// IsSuccess returns true when this get orgs org name settings ai o k response has a 2xx status code
func (o *GetOrgsOrgNameSettingsAiOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get orgs org name settings ai o k response has a 3xx status code
func (o *GetOrgsOrgNameSettingsAiOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs org name settings ai o k response has a 4xx status code
func (o *GetOrgsOrgNameSettingsAiOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get orgs org name settings ai o k response has a 5xx status code
func (o *GetOrgsOrgNameSettingsAiOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs org name settings ai o k response a status code equal to that given
func (o *GetOrgsOrgNameSettingsAiOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get orgs org name settings ai o k response
func (o *GetOrgsOrgNameSettingsAiOK) Code() int {
	return 200
}

func (o *GetOrgsOrgNameSettingsAiOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiOK %s", 200, payload)
}

func (o *GetOrgsOrgNameSettingsAiOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiOK %s", 200, payload)
}

func (o *GetOrgsOrgNameSettingsAiOK) GetPayload() *models.SettingsAISettings {
	return o.Payload
}

func (o *GetOrgsOrgNameSettingsAiOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SettingsAISettings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetOrgsOrgNameSettingsAiUnauthorized creates a GetOrgsOrgNameSettingsAiUnauthorized with default headers values
func NewGetOrgsOrgNameSettingsAiUnauthorized() *GetOrgsOrgNameSettingsAiUnauthorized {
	return &GetOrgsOrgNameSettingsAiUnauthorized{}
}

/*
GetOrgsOrgNameSettingsAiUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetOrgsOrgNameSettingsAiUnauthorized struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get orgs org name settings ai unauthorized response has a 2xx status code
func (o *GetOrgsOrgNameSettingsAiUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get orgs org name settings ai unauthorized response has a 3xx status code
func (o *GetOrgsOrgNameSettingsAiUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs org name settings ai unauthorized response has a 4xx status code
func (o *GetOrgsOrgNameSettingsAiUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get orgs org name settings ai unauthorized response has a 5xx status code
func (o *GetOrgsOrgNameSettingsAiUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs org name settings ai unauthorized response a status code equal to that given
func (o *GetOrgsOrgNameSettingsAiUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get orgs org name settings ai unauthorized response
func (o *GetOrgsOrgNameSettingsAiUnauthorized) Code() int {
	return 401
}

func (o *GetOrgsOrgNameSettingsAiUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiUnauthorized %s", 401, payload)
}

func (o *GetOrgsOrgNameSettingsAiUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiUnauthorized %s", 401, payload)
}

func (o *GetOrgsOrgNameSettingsAiUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetOrgsOrgNameSettingsAiUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetOrgsOrgNameSettingsAiNotFound creates a GetOrgsOrgNameSettingsAiNotFound with default headers values
func NewGetOrgsOrgNameSettingsAiNotFound() *GetOrgsOrgNameSettingsAiNotFound {
	return &GetOrgsOrgNameSettingsAiNotFound{}
}

/*
GetOrgsOrgNameSettingsAiNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetOrgsOrgNameSettingsAiNotFound struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this get orgs org name settings ai not found response has a 2xx status code
func (o *GetOrgsOrgNameSettingsAiNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get orgs org name settings ai not found response has a 3xx status code
func (o *GetOrgsOrgNameSettingsAiNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orgs org name settings ai not found response has a 4xx status code
func (o *GetOrgsOrgNameSettingsAiNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get orgs org name settings ai not found response has a 5xx status code
func (o *GetOrgsOrgNameSettingsAiNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get orgs org name settings ai not found response a status code equal to that given
func (o *GetOrgsOrgNameSettingsAiNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get orgs org name settings ai not found response
func (o *GetOrgsOrgNameSettingsAiNotFound) Code() int {
	return 404
}

func (o *GetOrgsOrgNameSettingsAiNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiNotFound %s", 404, payload)
}

func (o *GetOrgsOrgNameSettingsAiNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orgs/{orgName}/settings/ai][%d] getOrgsOrgNameSettingsAiNotFound %s", 404, payload)
}

func (o *GetOrgsOrgNameSettingsAiNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetOrgsOrgNameSettingsAiNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
