// Code generated by go-swagger; DO NOT EDIT.

package route_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/signadot/go-sdk/models"
)

// NewApplyRoutegroupParams creates a new ApplyRoutegroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplyRoutegroupParams() *ApplyRoutegroupParams {
	return &ApplyRoutegroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplyRoutegroupParamsWithTimeout creates a new ApplyRoutegroupParams object
// with the ability to set a timeout on a request.
func NewApplyRoutegroupParamsWithTimeout(timeout time.Duration) *ApplyRoutegroupParams {
	return &ApplyRoutegroupParams{
		timeout: timeout,
	}
}

// NewApplyRoutegroupParamsWithContext creates a new ApplyRoutegroupParams object
// with the ability to set a context for a request.
func NewApplyRoutegroupParamsWithContext(ctx context.Context) *ApplyRoutegroupParams {
	return &ApplyRoutegroupParams{
		Context: ctx,
	}
}

// NewApplyRoutegroupParamsWithHTTPClient creates a new ApplyRoutegroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplyRoutegroupParamsWithHTTPClient(client *http.Client) *ApplyRoutegroupParams {
	return &ApplyRoutegroupParams{
		HTTPClient: client,
	}
}

/* ApplyRoutegroupParams contains all the parameters to send to the API endpoint
   for the apply routegroup operation.

   Typically these are written to a http.Request.
*/
type ApplyRoutegroupParams struct {

	/* Data.

	   Request to create or update routegroup
	*/
	Data *models.RouteGroup

	/* OrgName.

	   Signadot Org Name
	*/
	OrgName string

	/* RoutegroupName.

	   RouteGroup Name
	*/
	RoutegroupName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the apply routegroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyRoutegroupParams) WithDefaults() *ApplyRoutegroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the apply routegroup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplyRoutegroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the apply routegroup params
func (o *ApplyRoutegroupParams) WithTimeout(timeout time.Duration) *ApplyRoutegroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the apply routegroup params
func (o *ApplyRoutegroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the apply routegroup params
func (o *ApplyRoutegroupParams) WithContext(ctx context.Context) *ApplyRoutegroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the apply routegroup params
func (o *ApplyRoutegroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the apply routegroup params
func (o *ApplyRoutegroupParams) WithHTTPClient(client *http.Client) *ApplyRoutegroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the apply routegroup params
func (o *ApplyRoutegroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the apply routegroup params
func (o *ApplyRoutegroupParams) WithData(data *models.RouteGroup) *ApplyRoutegroupParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the apply routegroup params
func (o *ApplyRoutegroupParams) SetData(data *models.RouteGroup) {
	o.Data = data
}

// WithOrgName adds the orgName to the apply routegroup params
func (o *ApplyRoutegroupParams) WithOrgName(orgName string) *ApplyRoutegroupParams {
	o.SetOrgName(orgName)
	return o
}

// SetOrgName adds the orgName to the apply routegroup params
func (o *ApplyRoutegroupParams) SetOrgName(orgName string) {
	o.OrgName = orgName
}

// WithRoutegroupName adds the routegroupName to the apply routegroup params
func (o *ApplyRoutegroupParams) WithRoutegroupName(routegroupName string) *ApplyRoutegroupParams {
	o.SetRoutegroupName(routegroupName)
	return o
}

// SetRoutegroupName adds the routegroupName to the apply routegroup params
func (o *ApplyRoutegroupParams) SetRoutegroupName(routegroupName string) {
	o.RoutegroupName = routegroupName
}

// WriteToRequest writes these params to a swagger request
func (o *ApplyRoutegroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param orgName
	if err := r.SetPathParam("orgName", o.OrgName); err != nil {
		return err
	}

	// path param routegroupName
	if err := r.SetPathParam("routegroupName", o.RoutegroupName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
