// Code generated by go-swagger; DO NOT EDIT.

package cluster

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new cluster API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new cluster API client with basic auth credentials.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new cluster API client with a bearer token for authentication.
//
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for cluster API.
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods.
type ClientService interface {

	// AddCluster add a cluster.
	AddCluster(params *AddClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddClusterOK, error)

	// AddClusterContext add a cluster.
	AddClusterContext(ctx context.Context, params *AddClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddClusterOK, error)

	// ClusterDevmeshAnalyze cluster dev mesh analyze.
	ClusterDevmeshAnalyze(params *ClusterDevmeshAnalyzeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ClusterDevmeshAnalyzeOK, error)

	// ClusterDevmeshAnalyzeContext cluster dev mesh analyze.
	ClusterDevmeshAnalyzeContext(ctx context.Context, params *ClusterDevmeshAnalyzeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ClusterDevmeshAnalyzeOK, error)

	// CreateClusterToken create cluster token.
	CreateClusterToken(params *CreateClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateClusterTokenOK, error)

	// CreateClusterTokenContext create cluster token.
	CreateClusterTokenContext(ctx context.Context, params *CreateClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateClusterTokenOK, error)

	// DeleteClusterToken delete cluster token.
	DeleteClusterToken(params *DeleteClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteClusterTokenOK, error)

	// DeleteClusterTokenContext delete cluster token.
	DeleteClusterTokenContext(ctx context.Context, params *DeleteClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteClusterTokenOK, error)

	// GetCluster get a cluster.
	GetCluster(params *GetClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterOK, error)

	// GetClusterContext get a cluster.
	GetClusterContext(ctx context.Context, params *GetClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterOK, error)

	// GetClusterToken get a cluster token.
	GetClusterToken(params *GetClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterTokenOK, error)

	// GetClusterTokenContext get a cluster token.
	GetClusterTokenContext(ctx context.Context, params *GetClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterTokenOK, error)

	// ListClusterTokens list cluster tokens.
	ListClusterTokens(params *ListClusterTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClusterTokensOK, error)

	// ListClusterTokensContext list cluster tokens.
	ListClusterTokensContext(ctx context.Context, params *ListClusterTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClusterTokensOK, error)

	// ListClusters list clusters.
	ListClusters(params *ListClustersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClustersOK, error)

	// ListClustersContext list clusters.
	ListClustersContext(ctx context.Context, params *ListClustersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClustersOK, error)

	// RemoveCluster remove a cluster.
	RemoveCluster(params *RemoveClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveClusterOK, error)

	// RemoveClusterContext remove a cluster.
	RemoveClusterContext(ctx context.Context, params *RemoveClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveClusterOK, error)

	SetTransport(transport runtime.ContextualTransport)
}

/*
AddClusteradds a cluster.

Add a Kubernetes cluster to Signadot..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.AddClusterContext] instead.
*/
func (a *Client) AddCluster(params *AddClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddClusterOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.AddClusterContext(ctx, params, authInfo, opts...)
}

/*
AddClusterContextadds a cluster.

Add a Kubernetes cluster to Signadot..

Do not use the deprecated [AddClusterParams.Context] with this method: it would be ignored.
*/
func (a *Client) AddClusterContext(ctx context.Context, params *AddClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AddClusterOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewAddClusterParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "add-cluster",
		Method:             "PUT",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddClusterReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*AddClusterOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for add-cluster: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ClusterDevmeshAnalyzeclusters dev mesh analyze.

Analyze DevMesh status for a given cluster.

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.ClusterDevmeshAnalyzeContext] instead.
*/
func (a *Client) ClusterDevmeshAnalyze(params *ClusterDevmeshAnalyzeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ClusterDevmeshAnalyzeOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ClusterDevmeshAnalyzeContext(ctx, params, authInfo, opts...)
}

/*
ClusterDevmeshAnalyzeContextclusters dev mesh analyze.

Analyze DevMesh status for a given cluster.

Do not use the deprecated [ClusterDevmeshAnalyzeParams.Context] with this method: it would be ignored.
*/
func (a *Client) ClusterDevmeshAnalyzeContext(ctx context.Context, params *ClusterDevmeshAnalyzeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ClusterDevmeshAnalyzeOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewClusterDevmeshAnalyzeParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "cluster-devmesh-analyze",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/devmesh/analyze",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ClusterDevmeshAnalyzeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ClusterDevmeshAnalyzeOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for cluster-devmesh-analyze: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
CreateClusterTokencreates cluster token.

Create a new token for connecting a cluster..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.CreateClusterTokenContext] instead.
*/
func (a *Client) CreateClusterToken(params *CreateClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateClusterTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.CreateClusterTokenContext(ctx, params, authInfo, opts...)
}

/*
CreateClusterTokenContextcreates cluster token.

Create a new token for connecting a cluster..

Do not use the deprecated [CreateClusterTokenParams.Context] with this method: it would be ignored.
*/
func (a *Client) CreateClusterTokenContext(ctx context.Context, params *CreateClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateClusterTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewCreateClusterTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "create-cluster-token",
		Method:             "POST",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/tokens",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateClusterTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*CreateClusterTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for create-cluster-token: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteClusterTokendeletes cluster token.

Delete a cluster token associated with a cluster..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.DeleteClusterTokenContext] instead.
*/
func (a *Client) DeleteClusterToken(params *DeleteClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteClusterTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.DeleteClusterTokenContext(ctx, params, authInfo, opts...)
}

/*
DeleteClusterTokenContextdeletes cluster token.

Delete a cluster token associated with a cluster..

Do not use the deprecated [DeleteClusterTokenParams.Context] with this method: it would be ignored.
*/
func (a *Client) DeleteClusterTokenContext(ctx context.Context, params *DeleteClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteClusterTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteClusterTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "delete-cluster-token",
		Method:             "DELETE",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/tokens/{tokenId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteClusterTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteClusterTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for delete-cluster-token: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetClustergets a cluster.

Get a cluster..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetClusterContext] instead.
*/
func (a *Client) GetCluster(params *GetClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetClusterContext(ctx, params, authInfo, opts...)
}

/*
GetClusterContextgets a cluster.

Get a cluster..

Do not use the deprecated [GetClusterParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetClusterContext(ctx context.Context, params *GetClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetClusterParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "get-cluster",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetClusterReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetClusterOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-cluster: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetClusterTokengets a cluster token.

Get a cluster token associated with a cluster..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.GetClusterTokenContext] instead.
*/
func (a *Client) GetClusterToken(params *GetClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterTokenOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.GetClusterTokenContext(ctx, params, authInfo, opts...)
}

/*
GetClusterTokenContextgets a cluster token.

Get a cluster token associated with a cluster..

Do not use the deprecated [GetClusterTokenParams.Context] with this method: it would be ignored.
*/
func (a *Client) GetClusterTokenContext(ctx context.Context, params *GetClusterTokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetClusterTokenOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetClusterTokenParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "get-cluster-token",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/tokens/{tokenId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetClusterTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetClusterTokenOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-cluster-token: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListClusterTokenslists cluster tokens.

List the cluster tokens associated with a cluster..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.ListClusterTokensContext] instead.
*/
func (a *Client) ListClusterTokens(params *ListClusterTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClusterTokensOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListClusterTokensContext(ctx, params, authInfo, opts...)
}

/*
ListClusterTokensContextlists cluster tokens.

List the cluster tokens associated with a cluster..

Do not use the deprecated [ListClusterTokensParams.Context] with this method: it would be ignored.
*/
func (a *Client) ListClusterTokensContext(ctx context.Context, params *ListClusterTokensParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClusterTokensOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListClusterTokensParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "list-cluster-tokens",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/tokens/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListClusterTokensReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListClusterTokensOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for list-cluster-tokens: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListClusterslists clusters.

List clusters..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.ListClustersContext] instead.
*/
func (a *Client) ListClusters(params *ListClustersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClustersOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.ListClustersContext(ctx, params, authInfo, opts...)
}

/*
ListClustersContextlists clusters.

List clusters..

Do not use the deprecated [ListClustersParams.Context] with this method: it would be ignored.
*/
func (a *Client) ListClustersContext(ctx context.Context, params *ListClustersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListClustersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewListClustersParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "list-clusters",
		Method:             "GET",
		PathPattern:        "/orgs/{orgName}/clusters/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListClustersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*ListClustersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for list-clusters: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RemoveClusterremoves a cluster.

Remove a Kubernetes cluster from Signadot..

This method does not support injected context.
However, timeout and opentracing contexts are honored whenever enabled.

If you need to pass a specific context, use [Client.RemoveClusterContext] instead.
*/
func (a *Client) RemoveCluster(params *RemoveClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveClusterOK, error) {
	var ctx context.Context
	if params.inner.ctx != nil {
		ctx = params.inner.ctx
	} else {
		ctx = context.Background()
	}

	return a.RemoveClusterContext(ctx, params, authInfo, opts...)
}

/*
RemoveClusterContextremoves a cluster.

Remove a Kubernetes cluster from Signadot..

Do not use the deprecated [RemoveClusterParams.Context] with this method: it would be ignored.
*/
func (a *Client) RemoveClusterContext(ctx context.Context, params *RemoveClusterParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RemoveClusterOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRemoveClusterParams()
	}

	op := &runtime.ClientOperation{
		ID:                 "remove-cluster",
		Method:             "DELETE",
		PathPattern:        "/orgs/{orgName}/clusters/{clusterName}/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RemoveClusterReader{formats: a.formats},
		AuthInfo:           authInfo,
		Client:             params.HTTPClient,
	}

	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.SubmitContext(ctx, op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RemoveClusterOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for remove-cluster: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ContextualTransport) {
	a.transport = transport
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ClusterParams].
	ctx context.Context
}
