// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CapturemetaScriptRef capturemeta script ref
//
// swagger:model capturemeta.ScriptRef
type CapturemetaScriptRef struct {

	// call number
	CallNum int64 `json:"callNum,omitempty"`

	// 1-based column (rune) number; 0 if column unknown
	Col int64 `json:"col,omitempty"`

	// filename
	File string `json:"file,omitempty"`

	// 1-based line number; 0 if line unknown
	Line int64 `json:"line,omitempty"`
}

// Validate validates this capturemeta script ref
func (m *CapturemetaScriptRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this capturemeta script ref based on context it is used
func (m *CapturemetaScriptRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CapturemetaScriptRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CapturemetaScriptRef) UnmarshalBinary(b []byte) error {
	var res CapturemetaScriptRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
