// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigPreviewConfig config preview config
//
// swagger:model config.PreviewConfig
type ConfigPreviewConfig struct {

	// CustomPreviewDomain is the base domain the preview server expects on
	// the leading label of an inbound Host, e.g. "preview.signadot.com".
	CustomPreviewDomain string `json:"customPreviewDomain,omitempty"`

	// Mode is "control-plane", "in-cluster", or "both" -- which front doors
	// preview traffic is expected to arrive through. It is a control-plane
	// routing input, not an operator one: the preview server serves every
	// vantage on one port and does not read this. Closing the in-cluster
	// door means not pointing an ingress at that port.
	Mode string `json:"mode,omitempty"`
}

// Validate validates this config preview config
func (m *ConfigPreviewConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config preview config based on context it is used
func (m *ConfigPreviewConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigPreviewConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigPreviewConfig) UnmarshalBinary(b []byte) error {
	var res ConfigPreviewConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
