// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigDevMeshConfig config dev mesh config
//
// swagger:model config.DevMeshConfig
type ConfigDevMeshConfig struct {

	// Enabled reports whether DevMesh sidecar injection is installed on this
	// cluster. Absent means enabled.
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this config dev mesh config
func (m *ConfigDevMeshConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config dev mesh config based on context it is used
func (m *ConfigDevMeshConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigDevMeshConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigDevMeshConfig) UnmarshalBinary(b []byte) error {
	var res ConfigDevMeshConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
