// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigControlPlaneConfig config control plane config
//
// swagger:model config.ControlPlaneConfig
type ConfigControlPlaneConfig struct {

	// control plane can be disabled
	Disabled bool `json:"disabled,omitempty"`

	// control plane proxy can be "enabled" or "disabled"
	Proxy string `json:"proxy,omitempty"`

	// tunnel addr
	TunnelAddr string `json:"tunnelAddr,omitempty"`

	// tunnel TLS
	TunnelTLS bool `json:"tunnelTLS,omitempty"`
}

// Validate validates this config control plane config
func (m *ConfigControlPlaneConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config control plane config based on context it is used
func (m *ConfigControlPlaneConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigControlPlaneConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigControlPlaneConfig) UnmarshalBinary(b []byte) error {
	var res ConfigControlPlaneConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
