// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EnvValueFromFork env value from fork
//
// swagger:model EnvValueFromFork
type EnvValueFromFork struct {

	// expression
	Expression string `json:"expression,omitempty"`

	// fork of
	ForkOf *ForkOf `json:"forkOf,omitempty"`
}

// Validate validates this env value from fork
func (m *EnvValueFromFork) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForkOf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnvValueFromFork) validateForkOf(formats strfmt.Registry) error {
	if swag.IsZero(m.ForkOf) { // not required
		return nil
	}

	if m.ForkOf != nil {
		if err := m.ForkOf.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("forkOf")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("forkOf")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this env value from fork based on the context it is used
func (m *EnvValueFromFork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateForkOf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EnvValueFromFork) contextValidateForkOf(ctx context.Context, formats strfmt.Registry) error {

	if m.ForkOf != nil {
		if err := m.ForkOf.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("forkOf")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("forkOf")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EnvValueFromFork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvValueFromFork) UnmarshalBinary(b []byte) error {
	var res EnvValueFromFork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
