// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobRunnerGroupExecutionsStatus job runner group executions status
//
// swagger:model jobRunnerGroup.ExecutionsStatus
type JobRunnerGroupExecutionsStatus struct {

	// completed
	Completed int64 `json:"completed,omitempty"`

	// queued
	Queued int64 `json:"queued,omitempty"`

	// running
	Running int64 `json:"running,omitempty"`
}

// Validate validates this job runner group executions status
func (m *JobRunnerGroupExecutionsStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job runner group executions status based on context it is used
func (m *JobRunnerGroupExecutionsStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobRunnerGroupExecutionsStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobRunnerGroupExecutionsStatus) UnmarshalBinary(b []byte) error {
	var res JobRunnerGroupExecutionsStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
