// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobUploadArtifact job upload artifact
//
// swagger:model job.UploadArtifact
type JobUploadArtifact struct {

	// meta
	Meta map[string]string `json:"meta,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this job upload artifact
func (m *JobUploadArtifact) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job upload artifact based on context it is used
func (m *JobUploadArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobUploadArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobUploadArtifact) UnmarshalBinary(b []byte) error {
	var res JobUploadArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
