// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobRunnerGroupSpec job runner group spec
//
// swagger:model jobRunnerGroup.Spec
type JobRunnerGroupSpec struct {

	// cluster
	Cluster string `json:"cluster,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// JobTimeout specifies the max job execution time of jobs running with this
	// RunnerGroup.  If not specified, it defaults to 30 minutes ("30m")
	JobTimeout string `json:"jobTimeout,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// pod template
	PodTemplate interface{} `json:"podTemplate,omitempty"`

	// ReusePods specifies whether JRG pods are reused after job executions.
	// If false (default), JRG pods are always recreated after each job.
	ReusePods bool `json:"reusePods,omitempty"`

	// scaling
	Scaling *JobRunnerGroupScaling `json:"scaling,omitempty"`
}

// Validate validates this job runner group spec
func (m *JobRunnerGroupSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScaling(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobRunnerGroupSpec) validateScaling(formats strfmt.Registry) error {
	if swag.IsZero(m.Scaling) { // not required
		return nil
	}

	if m.Scaling != nil {
		if err := m.Scaling.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scaling")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scaling")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this job runner group spec based on the context it is used
func (m *JobRunnerGroupSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScaling(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobRunnerGroupSpec) contextValidateScaling(ctx context.Context, formats strfmt.Registry) error {

	if m.Scaling != nil {

		if swag.IsZero(m.Scaling) { // not required
			return nil
		}

		if err := m.Scaling.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scaling")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("scaling")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JobRunnerGroupSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobRunnerGroupSpec) UnmarshalBinary(b []byte) error {
	var res JobRunnerGroupSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
