// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobRunnerGroupAutoScaling job runner group auto scaling
//
// swagger:model jobRunnerGroup.AutoScaling
type JobRunnerGroupAutoScaling struct {

	// max pods
	MaxPods int64 `json:"maxPods,omitempty"`

	// min pods
	MinPods int64 `json:"minPods,omitempty"`
}

// Validate validates this job runner group auto scaling
func (m *JobRunnerGroupAutoScaling) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job runner group auto scaling based on context it is used
func (m *JobRunnerGroupAutoScaling) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobRunnerGroupAutoScaling) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobRunnerGroupAutoScaling) UnmarshalBinary(b []byte) error {
	var res JobRunnerGroupAutoScaling
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
