// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// LogsLogType logs log type
//
// swagger:model logs.LogType
type LogsLogType string

func NewLogsLogType(value LogsLogType) *LogsLogType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated LogsLogType.
func (m LogsLogType) Pointer() *LogsLogType {
	return &m
}

const (

	// LogsLogTypeStdout captures enum value "stdout"
	LogsLogTypeStdout LogsLogType = "stdout"

	// LogsLogTypeStderr captures enum value "stderr"
	LogsLogTypeStderr LogsLogType = "stderr"
)

// for schema
var logsLogTypeEnum []any

func init() {
	var res []LogsLogType
	if err := json.Unmarshal([]byte(`["stdout","stderr"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		logsLogTypeEnum = append(logsLogTypeEnum, v)
	}
}

func (m LogsLogType) validateLogsLogTypeEnum(path, location string, value LogsLogType) error {
	if err := validate.EnumCase(path, location, value, logsLogTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this logs log type
func (m LogsLogType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateLogsLogTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this logs log type based on context it is used
func (m LogsLogType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
