// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanLogStatus plan log status
//
// swagger:model PlanLogStatus
type PlanLogStatus struct {

	// artifact
	Artifact *PlanArtifactRef `json:"artifact,omitempty"`

	// stream
	Stream LogsLogType `json:"stream,omitempty"`

	// Value holds the log content inline if small enough.
	Value string `json:"value,omitempty"`
}

// Validate validates this plan log status
func (m *PlanLogStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArtifact(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStream(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanLogStatus) validateArtifact(formats strfmt.Registry) error {
	if swag.IsZero(m.Artifact) { // not required
		return nil
	}

	if m.Artifact != nil {
		if err := m.Artifact.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("artifact")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("artifact")
			}

			return err
		}
	}

	return nil
}

func (m *PlanLogStatus) validateStream(formats strfmt.Registry) error {
	if swag.IsZero(m.Stream) { // not required
		return nil
	}

	if err := m.Stream.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("stream")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("stream")
		}

		return err
	}

	return nil
}

// ContextValidate validate this plan log status based on the context it is used
func (m *PlanLogStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArtifact(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStream(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanLogStatus) contextValidateArtifact(ctx context.Context, formats strfmt.Registry) error {

	if m.Artifact != nil {

		if swag.IsZero(m.Artifact) { // not required
			return nil
		}

		if err := m.Artifact.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("artifact")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("artifact")
			}

			return err
		}
	}

	return nil
}

func (m *PlanLogStatus) contextValidateStream(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Stream) { // not required
		return nil
	}

	if err := m.Stream.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("stream")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("stream")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlanLogStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanLogStatus) UnmarshalBinary(b []byte) error {
	var res PlanLogStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
