// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlansActionFrontMatter plans action front matter
//
// swagger:model plans.ActionFrontMatter
type PlansActionFrontMatter struct {

	// Requires declares runtime dependencies that must be present on the runner.
	// Each entry is a binary name with an optional semver constraint, e.g.
	// "node >= 20", "npx", "playwright".
	Requires []string `json:"requires"`
}

// Validate validates this plans action front matter
func (m *PlansActionFrontMatter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plans action front matter based on context it is used
func (m *PlansActionFrontMatter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlansActionFrontMatter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlansActionFrontMatter) UnmarshalBinary(b []byte) error {
	var res PlansActionFrontMatter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
