// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlansActionSpec plans action spec
//
// swagger:model plans.ActionSpec
type PlansActionSpec struct {

	// Body is the action implementation as markdown with code blocks.
	// Inputs and outputs are declared inline via \input{...} and \output{...} syntax.
	// Validation scripts are declared via ```validation fenced code blocks
	// and are extracted into Status.ValidationScript by the server.
	Body string `json:"body,omitempty"`

	// frontmatter
	Frontmatter *PlansActionFrontMatter `json:"frontmatter,omitempty"`

	// Published controls whether this action is visible and usable.
	Published bool `json:"published,omitempty"`
}

// Validate validates this plans action spec
func (m *PlansActionSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrontmatter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlansActionSpec) validateFrontmatter(formats strfmt.Registry) error {
	if swag.IsZero(m.Frontmatter) { // not required
		return nil
	}

	if m.Frontmatter != nil {
		if err := m.Frontmatter.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("frontmatter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("frontmatter")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this plans action spec based on the context it is used
func (m *PlansActionSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFrontmatter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlansActionSpec) contextValidateFrontmatter(ctx context.Context, formats strfmt.Registry) error {

	if m.Frontmatter != nil {

		if swag.IsZero(m.Frontmatter) { // not required
			return nil
		}

		if err := m.Frontmatter.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("frontmatter")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("frontmatter")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlansActionSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlansActionSpec) UnmarshalBinary(b []byte) error {
	var res PlansActionSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
