// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanStatus plan status
//
// swagger:model PlanStatus
type PlanStatus struct {

	// CompiledFrom is the planID of the source plan, if this plan was produced
	// by recompiling an existing plan via POST /plans/{id}/compile.
	CompiledFrom string `json:"compiledFrom,omitempty"`

	// CreatedAt is when the plan was created. Serialized as RFC3339.
	CreatedAt string `json:"createdAt,omitempty"`

	// created by
	CreatedBy *CreatedBy `json:"createdBy,omitempty"`

	// executions
	Executions int64 `json:"executions,omitempty"`

	// StepDependencies is the step dependency graph, computed from ref expressions.
	// Keys are step IDs; values are the step IDs that step depends on.
	StepDependencies map[string][]string `json:"stepDependencies,omitempty"`
}

// Validate validates this plan status
func (m *PlanStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanStatus) validateCreatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedBy) { // not required
		return nil
	}

	if m.CreatedBy != nil {
		if err := m.CreatedBy.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("createdBy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("createdBy")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this plan status based on the context it is used
func (m *PlanStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanStatus) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedBy != nil {

		if swag.IsZero(m.CreatedBy) { // not required
			return nil
		}

		if err := m.CreatedBy.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("createdBy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("createdBy")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlanStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanStatus) UnmarshalBinary(b []byte) error {
	var res PlanStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
