// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanValidateResponse plan validate response
//
// swagger:model PlanValidateResponse
type PlanValidateResponse struct {

	// Requires contains the result of each requirement check.
	Requires []*PlanRequireResult `json:"requires"`

	// script
	Script *PlanScriptResult `json:"script,omitempty"`
}

// Validate validates this plan validate response
func (m *PlanValidateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequires(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScript(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanValidateResponse) validateRequires(formats strfmt.Registry) error {
	if swag.IsZero(m.Requires) { // not required
		return nil
	}

	for i := 0; i < len(m.Requires); i++ {
		if swag.IsZero(m.Requires[i]) { // not required
			continue
		}

		if m.Requires[i] != nil {
			if err := m.Requires[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("requires" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("requires" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PlanValidateResponse) validateScript(formats strfmt.Registry) error {
	if swag.IsZero(m.Script) { // not required
		return nil
	}

	if m.Script != nil {
		if err := m.Script.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("script")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("script")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this plan validate response based on the context it is used
func (m *PlanValidateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRequires(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScript(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanValidateResponse) contextValidateRequires(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Requires); i++ {

		if m.Requires[i] != nil {

			if swag.IsZero(m.Requires[i]) { // not required
				return nil
			}

			if err := m.Requires[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("requires" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("requires" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *PlanValidateResponse) contextValidateScript(ctx context.Context, formats strfmt.Registry) error {

	if m.Script != nil {

		if swag.IsZero(m.Script) { // not required
			return nil
		}

		if err := m.Script.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("script")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("script")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlanValidateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanValidateResponse) UnmarshalBinary(b []byte) error {
	var res PlanValidateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
