// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlanRunnerGroupPodsStatus plan runner group pods status
//
// swagger:model planRunnerGroup.PodsStatus
type PlanRunnerGroupPodsStatus struct {

	// not ready
	NotReady int64 `json:"notReady,omitempty"`

	// ready
	Ready int64 `json:"ready,omitempty"`
}

// Validate validates this plan runner group pods status
func (m *PlanRunnerGroupPodsStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plan runner group pods status based on context it is used
func (m *PlanRunnerGroupPodsStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlanRunnerGroupPodsStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanRunnerGroupPodsStatus) UnmarshalBinary(b []byte) error {
	var res PlanRunnerGroupPodsStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
