// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PlansInputResolvedVia plans input resolved via
//
// swagger:model plans.InputResolvedVia
type PlansInputResolvedVia string

func NewPlansInputResolvedVia(value PlansInputResolvedVia) *PlansInputResolvedVia {
	return &value
}

// Pointer returns a pointer to a freshly-allocated PlansInputResolvedVia.
func (m PlansInputResolvedVia) Pointer() *PlansInputResolvedVia {
	return &m
}

const (

	// PlansInputResolvedViaLiteral captures enum value "literal"
	PlansInputResolvedViaLiteral PlansInputResolvedVia = "literal"

	// PlansInputResolvedViaCallerSecret captures enum value "callerSecret"
	PlansInputResolvedViaCallerSecret PlansInputResolvedVia = "callerSecret"

	// PlansInputResolvedViaRef captures enum value "ref"
	PlansInputResolvedViaRef PlansInputResolvedVia = "ref"

	// PlansInputResolvedViaDefault captures enum value "default"
	PlansInputResolvedViaDefault PlansInputResolvedVia = "default"

	// PlansInputResolvedViaUnbound captures enum value "unbound"
	PlansInputResolvedViaUnbound PlansInputResolvedVia = "unbound"
)

// for schema
var plansInputResolvedViaEnum []any

func init() {
	var res []PlansInputResolvedVia
	if err := json.Unmarshal([]byte(`["literal","callerSecret","ref","default","unbound"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		plansInputResolvedViaEnum = append(plansInputResolvedViaEnum, v)
	}
}

func (m PlansInputResolvedVia) validatePlansInputResolvedViaEnum(path, location string, value PlansInputResolvedVia) error {
	if err := validate.EnumCase(path, location, value, plansInputResolvedViaEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this plans input resolved via
func (m PlansInputResolvedVia) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePlansInputResolvedViaEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this plans input resolved via based on context it is used
func (m PlansInputResolvedVia) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
