// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourcepluginRunner resourceplugin runner
//
// swagger:model resourceplugin.Runner
type ResourcepluginRunner struct {

	// Base pod template
	BasePodTemplate string `json:"basePodTemplate,omitempty"`

	// Image for the runner instance
	Image string `json:"image,omitempty"`

	// Namespace to create this runner instance in
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this resourceplugin runner
func (m *ResourcepluginRunner) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resourceplugin runner based on context it is used
func (m *ResourcepluginRunner) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourcepluginRunner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcepluginRunner) UnmarshalBinary(b []byte) error {
	var res ResourcepluginRunner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
