// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourcepluginValueFromStep resourceplugin value from step
//
// swagger:model resourceplugin.ValueFromStep
type ResourcepluginValueFromStep struct {

	// Name of the step
	Name string `json:"name,omitempty"`

	// Name of the variable from the step
	Output string `json:"output,omitempty"`
}

// Validate validates this resourceplugin value from step
func (m *ResourcepluginValueFromStep) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resourceplugin value from step based on context it is used
func (m *ResourcepluginValueFromStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourcepluginValueFromStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcepluginValueFromStep) UnmarshalBinary(b []byte) error {
	var res ResourcepluginValueFromStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
