// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RolePermissions role permissions
//
// swagger:model RolePermissions
type RolePermissions struct {

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Permissions is the expanded set of concrete permissions this role grants
	// (wildcards resolved against the catalog).
	Permissions []string `json:"permissions"`
}

// Validate validates this role permissions
func (m *RolePermissions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role permissions based on context it is used
func (m *RolePermissions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RolePermissions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RolePermissions) UnmarshalBinary(b []byte) error {
	var res RolePermissions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
