// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RoutegroupsEndpoint routegroups endpoint
//
// swagger:model routegroups.Endpoint
type RoutegroupsEndpoint struct {

	// cluster
	Cluster string `json:"cluster,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this routegroups endpoint
func (m *RoutegroupsEndpoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this routegroups endpoint based on context it is used
func (m *RoutegroupsEndpoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoutegroupsEndpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoutegroupsEndpoint) UnmarshalBinary(b []byte) error {
	var res RoutegroupsEndpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
