// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RoutegroupSpecEndpoint routegroup spec endpoint
//
// swagger:model routegroup.SpecEndpoint
type RoutegroupSpecEndpoint struct {

	// name
	Name string `json:"name,omitempty"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this routegroup spec endpoint
func (m *RoutegroupSpecEndpoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this routegroup spec endpoint based on context it is used
func (m *RoutegroupSpecEndpoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RoutegroupSpecEndpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoutegroupSpecEndpoint) UnmarshalBinary(b []byte) error {
	var res RoutegroupSpecEndpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
