// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SandboxFileSourceMap sandbox file source map
//
// swagger:model sandbox.FileSourceMap
type SandboxFileSourceMap struct {

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// optional
	Optional bool `json:"optional,omitempty"`
}

// Validate validates this sandbox file source map
func (m *SandboxFileSourceMap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sandbox file source map based on context it is used
func (m *SandboxFileSourceMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SandboxFileSourceMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SandboxFileSourceMap) UnmarshalBinary(b []byte) error {
	var res SandboxFileSourceMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
