// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SandboxFileSourceResource sandbox file source resource
//
// swagger:model sandbox.FileSourceResource
type SandboxFileSourceResource struct {

	// name
	Name string `json:"name,omitempty"`

	// output key
	OutputKey string `json:"outputKey,omitempty"`
}

// Validate validates this sandbox file source resource
func (m *SandboxFileSourceResource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sandbox file source resource based on context it is used
func (m *SandboxFileSourceResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SandboxFileSourceResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SandboxFileSourceResource) UnmarshalBinary(b []byte) error {
	var res SandboxFileSourceResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
