// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SandboxesArgValueFrom sandboxes arg value from
//
// swagger:model sandboxes.ArgValueFrom
type SandboxesArgValueFrom struct {

	// forward
	Forward string `json:"forward,omitempty"`
}

// Validate validates this sandboxes arg value from
func (m *SandboxesArgValueFrom) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sandboxes arg value from based on context it is used
func (m *SandboxesArgValueFrom) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SandboxesArgValueFrom) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SandboxesArgValueFrom) UnmarshalBinary(b []byte) error {
	var res SandboxesArgValueFrom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
