// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SandboxesMiddlewareMatch sandboxes middleware match
//
// swagger:model sandboxes.MiddlewareMatch
type SandboxesMiddlewareMatch struct {

	// Workload specifies a glob which matches
	// each workload name in the spec.
	Workload string `json:"workload,omitempty"`
}

// Validate validates this sandboxes middleware match
func (m *SandboxesMiddlewareMatch) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sandboxes middleware match based on context it is used
func (m *SandboxesMiddlewareMatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SandboxesMiddlewareMatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SandboxesMiddlewareMatch) UnmarshalBinary(b []byte) error {
	var res SandboxesMiddlewareMatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
