// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SandboxesExplainStatusResponse sandboxes explain status response
//
// swagger:model sandboxes.ExplainStatusResponse
type SandboxesExplainStatusResponse struct {

	// Explanation is a natural-language explanation of why the sandbox
	// is in its current state and what, if anything, the user can do.
	Explanation string `json:"explanation,omitempty"`

	// sandbox status
	SandboxStatus *SandboxReadiness `json:"sandboxStatus,omitempty"`
}

// Validate validates this sandboxes explain status response
func (m *SandboxesExplainStatusResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSandboxStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SandboxesExplainStatusResponse) validateSandboxStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.SandboxStatus) { // not required
		return nil
	}

	if m.SandboxStatus != nil {
		if err := m.SandboxStatus.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sandboxStatus")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sandboxStatus")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this sandboxes explain status response based on the context it is used
func (m *SandboxesExplainStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSandboxStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SandboxesExplainStatusResponse) contextValidateSandboxStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.SandboxStatus != nil {

		if swag.IsZero(m.SandboxStatus) { // not required
			return nil
		}

		if err := m.SandboxStatus.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("sandboxStatus")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("sandboxStatus")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SandboxesExplainStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SandboxesExplainStatusResponse) UnmarshalBinary(b []byte) error {
	var res SandboxesExplainStatusResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
