// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TagMapping tag mapping
//
// swagger:model TagMapping
type TagMapping struct {

	// PlanID is the plan this tag pointed to during this period.
	PlanID string `json:"planID,omitempty"`

	// TaggedAt is when the tag was assigned to this plan. Serialized as RFC3339.
	TaggedAt string `json:"taggedAt,omitempty"`

	// UntaggedAt is when the tag was moved or deleted. Empty if current.
	UntaggedAt string `json:"untaggedAt,omitempty"`
}

// Validate validates this tag mapping
func (m *TagMapping) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tag mapping based on context it is used
func (m *TagMapping) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TagMapping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagMapping) UnmarshalBinary(b []byte) error {
	var res TagMapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
