// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestexecutionsAutoDiff testexecutions auto diff
//
// swagger:model testexecutions.AutoDiff
type TestexecutionsAutoDiff struct {

	// Enabled = true, requires the definition of a valid routing context
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this testexecutions auto diff
func (m *TestexecutionsAutoDiff) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this testexecutions auto diff based on context it is used
func (m *TestexecutionsAutoDiff) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestexecutionsAutoDiff) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestexecutionsAutoDiff) UnmarshalBinary(b []byte) error {
	var res TestexecutionsAutoDiff
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
